### ISSUE TITLE
Clean up CLI UI

### ISSUE THREAD

**Issue by sdruskat** [hermes-hmc/hermes#179]
Consider using vanilla Click subcommands instead of groups and the custom `WorkflowCommand` mechanism, and additionally add `chain=True` to enable Maven-like subcommand chaining:

`hermes clean harvest process curate`

The only thing we'd need to enable beyond the current implementation is "curation skipping" for cases where users don't want an extra curation step. Could be done via `hermes deposit --silent` or similar.

To test: Does chaining with arguments work correctly, e.g., `hermes clean harvest process curate deposit --auth-token=foo --file=README.md postprocess`?

**Comment by poikilotherm** [comment]
This is related and/or a duplicate of #137

**Comment by sdruskat** [comment]
Closing as duplicate of #137.
