### ISSUE TITLE
Declarative approach to settings

### ISSUE THREAD

**Issue by zyzzyxdonta** [hermes-hmc/hermes#219]
We should consider describing the settings for the hermes workflow in a declarative manner, e.g. using [pydantic settings](https://docs.pydantic.dev/latest/concepts/pydantic_settings/). This allows us to define the structure of the settings in one (obvious) place rather than throughout the imperative code. It also makes configuration less error-prone as everything is laid out explicitly rather than implicitly and it allows for validation on program startup.

**Comment by poikilotherm** [comment]
Sketch from meeting on 2023-10-25:

- Create a specification class infrastructure to express what kind of settings and/or command line arguments a plugin requires / offers.
- Add a base class method as API contract to retrieve the specifications
- Create a CLI argument parser with static methods that understands the specs and provides lookup
- Create a Config file parser with static methods that understands the specs and provides lookups
